Repository free-tomorrow/free-tomorrow, pull requests merged in 2022-02, with the labels that each got.

#1 Feat/component structure
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.scss
  src/App.test.js
  src/Components/Budget/Budget.js
  src/Components/Budget/Budget.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Homepage/Homepage.js
  src/Components/Homepage/Homepage.scss
  src/Components/Schedule/Schedule.js
  src/Components/Schedule/Schedule.scss
  src/Components/Share/Share.js
  src/Components/Share/Share.scss
  src/features/counter/Counter.js
  src/features/counter/Counter.module.css
  src/features/counter/counterAPI.js
  src/features/counter/counterSlice.js
  src/features/counter/counterSlice.spec.js
  src/index.css
  src/index.js
  src/index.scss
  src/sass/mixins.scss
  src/sass/variables.scss
  src/serviceWorker.js
  src/setupTests.js
  src/state/store.js
Labels: enhancement, display

#3 Refactor/styling
  package-lock.json
  src/App.scss
  src/Components/Header/Header.scss
  src/Components/Homepage/Homepage.js
  src/Components/Homepage/Homepage.scss
  src/assets/right_arrow.png
Labels: display

#5 Feat/calendar
  src/App.js
  src/App.scss
  src/Components/Calendar/Calendar.js
  src/Components/Calendar/Calendar.scss
  src/Components/Header/Header.scss
  src/Components/Homepage/Homepage.js
  src/Components/Homepage/Homepage.scss
  src/Components/Schedule/Schedule.js
  src/Components/Schedule/Schedule.scss
  src/assets/travel_aliens.png
  src/index.js
  src/sass/variables.scss
  src/state/store.js
  src/state/userSlice.js
Labels: display

#18 Feat/react calendar
  src/App.js
  src/Components/Schedule/Schedule.js
  src/Components/Schedule/Schedule.scss
  src/mockData.js
  src/state/tripSlice.js
  src/state/userSlice.js
Labels: feature, FE

#23 Feat/trip slice data
  src/state/tempTripSlice.js
  src/state/tripSlice.js
  src/state/userSlice.js
Labels: feature, FE

#29 Feat/initial cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/Homepage_spec.js
  cypress/integration/Login_spec.js
  cypress/integration/SignUp_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/Components/Calendar/Calendar.js
  src/Components/Calendar/Calendar.scss
Labels: feature, FE, testing

#43 Feat/trip card
  src/App.js
  src/Components/Dashboard/Dashboard.js
  src/Components/Dashboard/Dashboard.scss
  src/Components/Share/Share.js
  src/Components/Share/Share.scss
  src/Components/TripCard/TripCard.js
  src/Components/TripCard/TripCard.scss
  src/assets/ft_earth.png
  src/state/store.js
  src/state/tripSlice.js
Labels: FE, styling

#45 Feat/input validation
  cypress/integration/Login_spec.js
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
Labels: enhancement, FE, testing

#49 Feat/add to trip
  src/App.js
  src/Components/AddToTrip/AddToTrip.js
  src/Components/AddToTrip/AddToTrip.scss
  src/Components/Dashboard/Dashboard.js
  src/Components/Login/Login.js
  src/Components/Share/Share.js
  src/Components/Share/Share.scss
  src/state/tripSlice.js
  src/state/userSlice.js
Labels: FE, redux

#53 Feat/error page
  package-lock.json
  package.json
  src/App.js
  src/Components/Budget/Budget.js
  src/Components/Dashboard/Dashboard.js
  src/Components/ErrorPage/ErrorPage.js
  src/Components/ErrorPage/ErrorPage.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Homepage/Homepage.js
  src/Components/Homepage/Homepage.scss
  src/Components/Login/Login.js
  src/Components/TripCard/TripCard.js
  src/state/tripSlice.js
Labels: feature, FE, redux, styling

#54 Feat/trip cards
  src/Components/Dashboard/Dashboard.js
  src/Components/Schedule/Schedule.js
  src/Components/Share/Share.js
  src/Components/Share/Share.scss
  src/Components/TripCard/TripCard.js
  src/state/tripSlice.js
Labels: feature, FE, redux

#55 Style dashboard grid
  src/App.scss
  src/Components/Dashboard/Dashboard.js
  src/Components/Dashboard/Dashboard.scss
  src/Components/Header/Header.scss
  src/Components/Homepage/Homepage.scss
  src/Components/TripCard/TripCard.js
  src/Components/TripCard/TripCard.scss
  src/sass/variables.scss
Labels: FE

#57 Bugfix/calendar
  src/Components/Budget/Budget.js
  src/Components/Budget/Budget.scss
  src/Components/Header/Header.scss
  src/Components/Schedule/Schedule.js
  src/Components/Schedule/Schedule.scss
Labels: FE

#59 Refactor/input validation
  src/Components/AddToTrip/AddToTrip.js
  src/Components/AddToTrip/AddToTrip.scss
  src/Components/Dashboard/Dashboard.js
  src/Components/Header/Header.js
  src/Components/Login/Login.js
  src/Components/Schedule/Schedule.js
  src/Components/Share/Share.js
  src/Components/SignUp/SignUp.js
  src/state/tripSlice.js
Labels: enhancement, FE, error handling

#61 Refactor/cypress
  .gitignore
  .netlify/state.json
  cypress/integration/Budget_spec.js
  cypress/integration/Dashboard_spec.js
  cypress/integration/Schedule_spec.js
  cypress/integration/Share_spec.js
  cypress/integration/SignUp_spec.js
  cypress/screenshots/2-advanced-examples/misc.spec.js/my-image.png
  cypress/screenshots/Homepage_spec.js/Homepage -- should have a sample test -- before each hook (failed).png
  cypress/screenshots/Login_spec.js/Login page -- should have a sample test -- before each hook (failed).png
  cypress/screenshots/SignUp_spec.js/SignUp page -- should have a sample test -- before each hook (failed).png
  cypress/videos/1-getting-started/todo.spec.js.mp4
  cypress/videos/2-advanced-examples/actions.spec.js.mp4
  cypress/videos/2-advanced-examples/aliasing.spec.js.mp4
  cypress/videos/2-advanced-examples/assertions.spec.js.mp4
  cypress/videos/2-advanced-examples/connectors.spec.js.mp4
  cypress/videos/2-advanced-examples/cookies.spec.js.mp4
  cypress/videos/2-advanced-examples/cypress_api.spec.js.mp4
  cypress/videos/2-advanced-examples/files.spec.js.mp4
  cypress/videos/2-advanced-examples/local_storage.spec.js.mp4
  cypress/videos/2-advanced-examples/location.spec.js.mp4
  cypress/videos/2-advanced-examples/misc.spec.js.mp4
  cypress/videos/2-advanced-examples/navigation.spec.js.mp4
  cypress/videos/2-advanced-examples/network_requests.spec.js.mp4
  cypress/videos/2-advanced-examples/querying.spec.js.mp4
  cypress/videos/2-advanced-examples/spies_stubs_clocks.spec.js.mp4
  cypress/videos/2-advanced-examples/traversal.spec.js.mp4
  cypress/videos/2-advanced-examples/utilities.spec.js.mp4
  cypress/videos/2-advanced-examples/viewport.spec.js.mp4
  cypress/videos/2-advanced-examples/waiting.spec.js.mp4
  cypress/videos/2-advanced-examples/window.spec.js.mp4
  cypress/videos/Budget_spec.js.mp4
  cypress/videos/Dashboard_spec.js.mp4
  cypress/videos/Homepage_spec.js.mp4
  cypress/videos/Login_spec.js.mp4
  cypress/videos/Schedule_spec.js.mp4
  cypress/videos/Share_spec.js.mp4
  cypress/videos/SignUp_spec.js.mp4
  src/Components/Dashboard/Dashboard.js
  src/Components/Header/Header.js
  src/Components/SignUp/SignUp.js
  src/state/userSlice.js
Labels: FE, testing

#63 Refactor/error handling
  src/Components/Header/Header.js
  src/Components/Schedule/Schedule.js
  src/state/store.js
  src/state/userSlice.js
Labels: refactor, FE, error handling

#64 Refactor/share
  package-lock.json
  package.json
  src/Components/AddToTrip/AddToTrip.js
  src/Components/AddToTrip/AddToTrip.scss
  src/Components/Dashboard/Dashboard.js
  src/Components/Dashboard/Dashboard.scss
  src/Components/Homepage/Homepage.scss
  src/Components/Login/Login.scss
  src/Components/Schedule/Schedule.scss
  src/Components/Share/Share.js
  src/Components/Share/Share.scss
  src/assets/copy_icon.png
Labels: refactor, feature, FE, redux, styling

#69 Add styling to and change size of dashboard cards
  src/Components/Dashboard/Dashboard.scss
  src/Components/TripCard/TripCard.scss
Labels: refactor, FE, styling

#70 Refactor/page sizing
  src/Components/Budget/Budget.scss
  src/Components/Header/Header.scss
  src/Components/Schedule/Schedule.scss
Labels: refactor, FE, styling
